### ISSUE TITLE
The directive "@specifiedBy" can only be used once at this location

### ISSUE THREAD

**Issue by ejkg** [B2o5T/graphql-eslint#1085]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

I am unable to run linting on any of my GraphQL Schema files. Literally, every single file has the same issue, even if I change a comment in a file. I have a pre-commit hook (husky) that lints our staged files. Whenever there is a graphql file in the staged files it throws the same error.

I can also reproduce in just a normal run of `yarn run lint` which resolves to `eslint src` run within the npm script context. 

```
Error: Error while loading rule '@graphql-eslint/no-unreachable-types': Error while loading schema: The directive "@specifiedBy" can only be used once at this location.
```

We're not using this `@specifiedBy` directive anywhere in our codebase. It might be in some dependency, but I'm not really sure where. All out of ideas could use some help!

Here's the output (modified ofc) from my `$ eslint src` output
```
yarn lint
yarn run v1.22.18
$ eslint src

Oops! Something went wrong! :(

ESLint: 8.17.0

Error: Error while loading rule '@graphql-eslint/no-unreachable-types': Error while loading schema: The directive "@specifiedBy" can only be used once at this location.
Occurred while linting /path/to/project/src/graphql/modules/my-module/module-schema.graphql
    at assertValidSDL (/path/to/project/node_modules/graphql/validation/validate.js:135:11)
    at Object.buildASTSchema (/path/to/project/node_modules/graphql/utilities/buildASTSchema.js:44:34)
    at makeExecutableSchema (/path/to/project/node_modules/@graphql-tools/schema/index.js:495:26)
    at Object.mergeSchemas (/path/to/project/node_modules/@graphql-tools/schema/index.js:532:12)
    at Object.loadSchemaSync (/path/to/project/node_modules/@graphql-tools/load/index.js:639:29)
    at LoadersRegistry.loadSchemaSync (/path/to/project/node_modules/graphql-config/index.js:563:25)
    at GraphQLProjectConfig.loadSchemaSync (/path/to/project/node_modules/graphql-config/index.js:450:56)
    at getSchema (/path/to/project/node_modules/@graphql-eslint/eslint-plugin/index.js:4168:33)
    at Object.parseForESLint (/path/to/project/node_modules/@graphql-eslint/eslint-plugin/index.js:4377:24)
    at parse (/path/to/project/node_modules/eslint/lib/linter/linter.js:805:22)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
1. Have GraphQL Schema files
2. Lint them.

**Expected behavior**
They should be linted.

**Environment:**

- OS: macOS 12.4
- `@graphql-eslint/eslint-plugin`: 3.10.4
- Node.js: 16.14

**Additional context**

TBD

**Comment by ejkg** [comment]
I was able to solve it, so I'll close. I'll leave some tips for anyone else who experiences something like this. This ended up being an issue with [GraphQL Mesh](https://github.com/Urigo/graphql-mesh) an orchestration framework that generates schemas and SDKs from remote data providers. Those schemas get placed in a temp folder that VSCode does not index, which is why I was not able to find the issue with a global search.

Short answer: Just make sure you regenerate any generated schema files you have.
