### ISSUE TITLE
alphabetize fails when property is aliased

### ISSUE THREAD

**Issue by gajus** [B2o5T/graphql-eslint#1113]
Input code:

```graphql
mutation CreateCryptoManualPayoutMutation(
  $input: CreateCryptoManualPayoutInput!
) {
  createCryptoManualPayout(input: $input) {
    errors {
      __typename
      message
    }
    userAccount {
      transactionHistory {
        edges {
          node {
            __typename
            contraReferenceId
            contraStatus
            createdAt
            id
            ... on StripePayoutV2 {
              amountCents
              createdAt
              payoutCurrency: currency
              estimatedArrivalAt
              externalAccount {
                id
                isDefault
              }
              id
              status
              type
            }
            ... on CryptoPayout {
              amountCents
              amountInCrypto
              cryptoPayoutCurrency: currency
              foreignPayoutId
              cryptoCurrencyAddress {
                address
                canDelete
                currency
                id
                isDefault
                label
              }
            }
          }
        }
      }
    }
  }
}

```

Error:

```
TypeError: Cannot read properties of undefined (reading '0')
Occurred while linting /Users/gajus/Documents/dev/contra/contra-api/test/documents/mutations/createCryptoManualPayout.graphql:18
Rule: "@graphql-eslint/alphabetize"
    at SourceCode.getCommentsBefore (/Users/gajus/Documents/dev/contra/contra-api/node_modules/eslint/lib/source-code/token-store/index.js:590:30)
    at getBeforeComments (/Users/gajus/Documents/dev/contra/contra-api/node_modules/@graphql-eslint/eslint-plugin/index.js:719:47)
    at getRangeWithComments (/Users/gajus/Documents/dev/contra/contra-api/node_modules/@graphql-eslint/eslint-plugin/index.js:743:42)
    at Object.fix (/Users/gajus/Documents/dev/contra/contra-api/node_modules/@graphql-eslint/eslint-plugin/index.js:780:43)
    at fix.next (<anonymous>)
    at Function.from (<anonymous>)
    at normalizeFixes (/Users/gajus/Documents/dev/contra/contra-api/node_modules/eslint/lib/linter/report-translator.js:197:33)
    at /Users/gajus/Documents/dev/contra/contra-api/node_modules/eslint/lib/linter/report-translator.js:364:49
    at Object.report (/Users/gajus/Documents/dev/contra/contra-api/node_modules/eslint/lib/linter/linter.js:1085:41)
    at checkNodes (/Users/gajus/Documents/dev/contra/contra-api/node_modules/@graphql-eslint/eslint-plugin/index.js:772:25)
```

This only fails when alias (such as `payoutCurrency: currency`) is present in the query.

**Comment by B2o5T** [comment]
thanks, fixed in [@graphql-eslint/eslint-plugin@3.10.6](https://github.com/B2o5T/graphql-eslint/releases/tag/%40graphql-eslint%2Feslint-plugin%403.10.6)
